### ISSUE TITLE
nvidia-docker跑demo训练程序出错

### ISSUE THREAD

**Issue by wuqi930907** [PaddlePaddle/DeepSpeech#149]
我用nvidia-docker（sudo nvidia-docker run -it -v $(pwd)/DeepSpeech:/DeepSpeech paddlepaddle/deep_speech:latest-gpu /bin/bash）在8块显卡上跑训练程序DeepSpeech/aishell/run_train.sh，出错了，请问这是怎么回事？代码一点没有改

Pass: 9, Batch: 1500, TrainCost: 1.245488
...................................................................................................
Pass: 9, Batch: 1600, TrainCost: 1.278968
...................................................................................................
Pass: 9, Batch: 1700, TrainCost: 1.278138
...................................................................................................
Pass: 9, Batch: 1800, TrainCost: 1.370887
...........................................................................
------- Time: 2829 sec, Pass: 9, ValidationCost: 1.88582897921
...................................................................................................Exception in thread Thread-21:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/DeepSpeech/data_utils/utility.py", line 153, in flush_worker
sample = in_queue.get()
File "", line 2, in get
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer

Pass: 10, Batch: 100, TrainCost: 0.892535
.....................................Process Process-376:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
while order_id != out_order[0]:
File "", line 2, in getitem
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-373:
Process Process-372:
Traceback (most recent call last):
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
while order_id != out_order[0]:
File "", line 2, in getitem
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
kind, result = conn.recv()
self.run()
IOError: [Errno 104] Connection reset by peer
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
Process Process-367:
self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
while order_id != out_order[0]:
File "", line 2, in getitem
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
Process Process-371:
Traceback (most recent call last):
while order_id != out_order[0]:
File "", line 2, in getitem
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
kind, result = conn.recv()
EOFError
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
kind, result = conn.recv()
while order_id != out_order[0]:
File "", line 2, in getitem
EOFError
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
kind, result = conn.recv()
EOFError
Process Process-374:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
Process Process-368:
Traceback (most recent call last):
while order_id != out_order[0]:
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
File "", line 2, in getitem
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/DeepSpeech/data_utils/utility.py", line 138, in order_handle_worker
kind, result = conn.recv()
out_order[0] += 1
File "", line 2, in getitem
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
Process Process-365:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
kind, result = conn.recv()
EOFError
Process Process-375:
IOError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
while order_id != out_order[0]:
File "", line 2, in getitem
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
while order_id != out_order[0]:
File "", line 2, in getitem
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-364:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
while order_id != out_order[0]:
File "", line 2, in getitem
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-369:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
while order_id != out_order[0]:
File "", line 2, in getitem
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-370:
Process Process-377:
Traceback (most recent call last):
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self.run()
self._target(*self._args, **self._kwargs)
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
while order_id != out_order[0]:
File "", line 2, in getitem
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-362:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/DeepSpeech/data_utils/utility.py", line 121, in order_read_worker
in_queue.put((order_id, sample))
File "", line 2, in put
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
kind, result = conn.recv()
EOFError
Process Process-363:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
while order_id != out_order[0]:
File "", line 2, in getitem
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-366:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
while order_id != out_order[0]:
File "", line 2, in getitem
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
kind, result = conn.recv()
EOFError
Process Process-378:
Traceback (most recent call last):
File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
while order_id != out_order[0]:
File "", line 2, in getitem
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
self._target(*self._args, **self._kwargs)
File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
while order_id != out_order[0]:
File "", line 2, in getitem
File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer

**Comment by kuke** [comment]
@wuqi930907 看起来像multiprocessing中的bug，你可以复现这个问题吗？

**Comment by wuqi930907** [comment]
可以的，实验了三次一直出这个错误。而且关掉终端之后，想要再次连接nvidia-docker的时候会出现如下的错误：
docker: Error response from daemon: connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused".
重启后才能连上，请问是我哪里操作错误了吗？
还有我没有使用docker的时候在Ubuntu14.04上配置环境，运行了setup.sh之后一切都安装成功了，python目录里面也有了swig_decoders模块的包，可是运行还是会提示：
ImportError: No module named swig_decoders
但是我在ubuntu16.04上安装环境就完成成功的，请问你们的环境是不是只支持ubuntu16.04？ @kuke

**Comment by kuke** [comment]
@wuqi930907 multiprocessing这个报错比较奇怪，我们看能不能找到一台机器复现你的错误。
退出docker不应该直接关掉terminal，你可以用exit或者```ctrl+D```来退出；decoder有若干依赖需要正确安装，你可以到```decoders/swig```这个目录下直接运行 ```setup.sh```这个脚本，注意安装日志中的报错，一般解决完了这些报错之后decoder的安装就没问题了。

**Comment by wuqi930907** [comment]
好的，谢谢 @kuke

**Comment by loongw** [comment]
有worker进程提前退出了（例如因内存不足的时候被系统kill了），就会出现此问题。

**Comment by wuqi930907** [comment]
谢谢提醒，但是我们的机器物理内存是128G，8张显卡都是12G的，应该不会是内存不足 @loongw

**Comment by loongw** [comment]
@wuqi930907 目前这个DeepSpeech在某些环境下有严重的资源泄露(See #148 )，你可以监视一下你的系统内存，看是不是被吃光啦。如果是泄露问题，可以应用这个补丁(#154)再试试。

**Comment by wuqi930907** [comment]
@loongw 好的，谢谢，我有空试验下
