### ISSUE TITLE
训练过程中 Connection reset by peer，“ managers.py", line 759,  result = conn.recv() IOError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by bolt163** [PaddlePaddle/DeepSpeech#181]
batch_size调成24 没有OOM， 第0个Pass训练正常，第1个Pass报 Connection reset by peer， 什么情况

...................................................................................................
Pass: 1, Batch: 2100, TrainCost: 8.552184
...................................................................................................
Pass: 1, Batch: 2200, TrainCost: 7.938597
...................................................................................................
Pass: 1, Batch: 2300, TrainCost: 8.337096
...................................................................................................
Pass: 1, Batch: 2400, TrainCost: 8.301428
...................................................................................................
Pass: 1, Batch: 2500, TrainCost: 7.078673
...................................................................................................
Pass: 1, Batch: 2600, TrainCost: 8.098217
...................................................................................................
Pass: 1, Batch: 2700, TrainCost: 8.403698
...................................................................................................
Pass: 1, Batch: 2800, TrainCost: 7.654552
...................................................................................................
Pass: 1, Batch: 2900, TrainCost: 7.540778
...................................................................................................
Pass: 1, Batch: 3000, TrainCost: 7.034502
...................................................................................................
Pass: 1, Batch: 3100, TrainCost: 8.303614
...................................................................................................
Pass: 1, Batch: 3200, TrainCost: 7.362420
...................................................................................................
Pass: 1, Batch: 3300, TrainCost: 8.457884
...................................................................................................
Pass: 1, Batch: 3400, TrainCost: 8.275194
...................................................................................................
Pass: 1, Batch: 3500, TrainCost: 7.887627
...................................................................................................
Pass: 1, Batch: 3600, TrainCost: 9.091355
...................................................................................................
Pass: 1, Batch: 3700, TrainCost: 7.678354
...................................................................................................
Pass: 1, Batch: 3800, TrainCost: 8.109676
...................................................................................................
Pass: 1, Batch: 3900, TrainCost: 8.876282
...................................................................................................
Pass: 1, Batch: 4000, TrainCost: 8.288002
...................................................................................................
Pass: 1, Batch: 4100, TrainCost: 7.990575
...................................................................................................
Pass: 1, Batch: 4200, TrainCost: 7.985103
...................................................................................................
Pass: 1, Batch: 4300, TrainCost: 7.639118
...................................................................................................
Pass: 1, Batch: 4400, TrainCost: 8.015420
...................................................................................................
Pass: 1, Batch: 4500, TrainCost: 7.916594
...................................................................................................
Pass: 1, Batch: 4600, TrainCost: 8.564386
...................................................................................................
Pass: 1, Batch: 4700, TrainCost: 8.309537
...................................................................................................
Pass: 1, Batch: 4800, TrainCost: 8.294658
...Exception in thread Thread-3:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 153, in flush_worker
    sample = in_queue.get()
  File "<string>", line 2, in get
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe

.....................Process Process-46:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-43:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-51:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    while order_id != out_order[0]:
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-53:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-42:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-47:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
Process Process-49:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker

**Comment by bolt163** [comment]
【今天同遇到】
...................................................................................................
Pass: 2, Batch: 3900, TrainCost: 3.124246
...................................................................................................
Pass: 2, Batch: 4000, TrainCost: 3.474351
...................................................................................................
Pass: 2, Batch: 4100, TrainCost: 3.645388
...................................................................................................
Pass: 2, Batch: 4200, TrainCost: 3.441009
...................................................................................................
Pass: 2, Batch: 4300, TrainCost: 3.315603
...................................................................................................
Pass: 2, Batch: 4400, TrainCost: 3.641322
...............................................
------- Time: 11173 sec,  Pass: 2, ValidationCost: 8.36927454867
...................................................................................................
Pass: 3, Batch: 100, TrainCost: 2.205036
...................................................................................................
Pass: 3, Batch: 200, TrainCost: 1.730144
...................................................................................................
Pass: 3, Batch: 300, TrainCost: 2.222765
...................................................................................................
Pass: 3, Batch: 400, TrainCost: 1.938759
...................................................................................................
Pass: 3, Batch: 500, TrainCost: 2.243470
...................................................................................................
Pass: 3, Batch: 600, TrainCost: 2.230025
...................................................................................................
Pass: 3, Batch: 700, TrainCost: 2.061182
...................................................................................................
Pass: 3, Batch: 800, TrainCost: 2.278065
...................................................................................................
Pass: 3, Batch: 900, TrainCost: 2.302279
...................................................................................................
Pass: 3, Batch: 1000, TrainCost: 2.129933
...................................................................................................
Pass: 3, Batch: 1100, TrainCost: 2.114630
...................................................................................................
Pass: 3, Batch: 1200, TrainCost: 2.161716
...................................................................................................
Pass: 3, Batch: 1300, TrainCost: 2.043306
...................................................................................................
Pass: 3, Batch: 1400, TrainCost: 2.241741
...................................................................................................
Pass: 3, Batch: 1500, TrainCost: 2.453839
...................................................................................................
Pass: 3, Batch: 1600, TrainCost: 2.127826
...................................................................................................
Pass: 3, Batch: 1700, TrainCost: 2.733970
...................................................................................................
Pass: 3, Batch: 1800, TrainCost: 2.457839
...................................................................................................
Pass: 3, Batch: 1900, TrainCost: 2.277187
...................................................................................................
Pass: 3, Batch: 2000, TrainCost: 2.233375
...................................................................................................
Pass: 3, Batch: 2100, TrainCost: 2.253250
...................................................................................................
Pass: 3, Batch: 2200, TrainCost: 2.169551
...................................................................................................
Pass: 3, Batch: 2300, TrainCost: 2.139775
...................................................................................................
Pass: 3, Batch: 2400, TrainCost: 2.303660
...................................................................................................
Pass: 3, Batch: 2500, TrainCost: 2.260985
...................................................................................................
Pass: 3, Batch: 2600, TrainCost: 2.209232
...................................................................................................
Pass: 3, Batch: 2700, TrainCost: 2.201921
...................................................................................................
Pass: 3, Batch: 2800, TrainCost: 2.503569
...................................................................................................
Pass: 3, Batch: 2900, TrainCost: 2.250824
...................................................................................................
Pass: 3, Batch: 3000, TrainCost: 2.703608
...................................................................................................
Pass: 3, Batch: 3100, TrainCost: 2.822674
...................................................................................................
Pass: 3, Batch: 3200, TrainCost: 2.655923
...................................................................................................
Pass: 3, Batch: 3300, TrainCost: 2.930974
...................................................................................................
Pass: 3, Batch: 3400, TrainCost: 2.673765
...................................................................................................
Pass: 3, Batch: 3500, TrainCost: 2.423031
...................................................................................................
Pass: 3, Batch: 3600, TrainCost: 2.597083
...................................................................................................
Pass: 3, Batch: 3700, TrainCost: 2.343953
...................................................................................................
Pass: 3, Batch: 3800, TrainCost: 2.587302
...................................................................................................
Pass: 3, Batch: 3900, TrainCost: 2.849032
...................................................................................................
Pass: 3, Batch: 4000, TrainCost: 2.931251
...................................................................................................
Pass: 3, Batch: 4100, TrainCost: 2.766392
...................................................................................................
Pass: 3, Batch: 4200, TrainCost: 2.906978
...................................................................................................
Pass: 3, Batch: 4300, TrainCost: 2.733018
...................................................................................................
Pass: 3, Batch: 4400, TrainCost: 2.553525
...............................................
------- Time: 11177 sec,  Pass: 3, ValidationCost: 8.26478868847
...................................................................................................
Pass: 4, Batch: 100, TrainCost: 1.707477
...................................................................................................
Pass: 4, Batch: 200, TrainCost: 1.723055
...................................................................................................
Pass: 4, Batch: 300, TrainCost: 1.452391
...................................................................................................
Pass: 4, Batch: 400, TrainCost: 1.390816
...................................................................................................
Pass: 4, Batch: 500, TrainCost: 1.459532
...................................................................................................
Pass: 4, Batch: 600, TrainCost: 1.488929
...................................................................................................
Pass: 4, Batch: 700, TrainCost: 1.764642
...................................................................................................
Pass: 4, Batch: 800, TrainCost: 1.642992
...................................................................................................
Pass: 4, Batch: 900, TrainCost: 2.114128
...................................................................................................
Pass: 4, Batch: 1000, TrainCost: 1.896314
...................................................................................................
Pass: 4, Batch: 1100, TrainCost: 1.972974
...................................................................................................
Pass: 4, Batch: 1200, TrainCost: 1.709793
...................................................................................................
Pass: 4, Batch: 1300, TrainCost: 1.950485
...................................................................................................
Pass: 4, Batch: 1400, TrainCost: 2.113540
...................................................................................................
Pass: 4, Batch: 1500, TrainCost: 1.814212
...................................................................................................
Pass: 4, Batch: 1600, TrainCost: 1.716949
...................................................................................................
Pass: 4, Batch: 1700, TrainCost: 1.539577
...................................................................................................
Pass: 4, Batch: 1800, TrainCost: 1.868563
...................................................................................................
Pass: 4, Batch: 1900, TrainCost: 1.885937
...................................................................................................
Pass: 4, Batch: 2000, TrainCost: 1.760929
...................................................................................................
Pass: 4, Batch: 2100, TrainCost: 1.871003
...................................................................................................
Pass: 4, Batch: 2200, TrainCost: 1.767099
...................................................................................................
Pass: 4, Batch: 2300, TrainCost: 1.890970
...................................................................................................
Pass: 4, Batch: 2400, TrainCost: 1.730810
...................................................................................................
Pass: 4, Batch: 2500, TrainCost: 1.790033
...................................................................................................
Pass: 4, Batch: 2600, TrainCost: 1.819861
...................................................................................................
Pass: 4, Batch: 2700, TrainCost: 2.008179
...................................................................................................
Pass: 4, Batch: 2800, TrainCost: 1.947404
...................................................................................................
Pass: 4, Batch: 2900, TrainCost: 2.022919
...................................................................................................
Pass: 4, Batch: 3000, TrainCost: 1.770177
...................................................................................................
Pass: 4, Batch: 3100, TrainCost: 1.804909
...................................................................................................
Pass: 4, Batch: 3200, TrainCost: 1.948628
...................................................................................................
Pass: 4, Batch: 3300, TrainCost: 1.857643
...................................................................................................
Pass: 4, Batch: 3400, TrainCost: 1.871495
...................................................................................................
Pass: 4, Batch: 3500, TrainCost: 1.873113
...................................................................................................
Pass: 4, Batch: 3600, TrainCost: 1.850358
...................................................................................................
Pass: 4, Batch: 3700, TrainCost: 1.848986
...................................................................................................
Pass: 4, Batch: 3800, TrainCost: 2.109548
...................................................................................................
Pass: 4, Batch: 3900, TrainCost: 2.099640
...................................................................................................
Pass: 4, Batch: 4000, TrainCost: 1.922527
...................................................................................................
Pass: 4, Batch: 4100, TrainCost: 2.326818
...................................................................................................
Pass: 4, Batch: 4200, TrainCost: 2.150745
...................................................................................................
Pass: 4, Batch: 4300, TrainCost: 2.130542
...................................................................................................
Pass: 4, Batch: 4400, TrainCost: 2.155663
...............................................Exception in thread Thread-10:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 153, in flush_worker
    sample = in_queue.get()
  File "<string>", line 2, in get
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: got end of file during message

Process Process-166:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
Process Process-171:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
Process Process-168:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
Process Process-172:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
Process Process-178:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
Process Process-175:
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
Process Process-179:
    kind, result = conn.recv()
Traceback (most recent call last):
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
EOFError
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    kind, result = conn.recv()
EOFError
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
Process Process-164:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 121, in order_read_worker
    in_queue.put((order_id, sample))
  File "<string>", line 2, in put
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
Process Process-170:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    kind, result = conn.recv()
EOFError
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
Process Process-165:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
Process Process-176:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
Process Process-167:
EOFError
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
Process Process-173:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
Process Process-174:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
Process Process-169:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-177:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
    kind, result = conn.recv()
EOFError
Process Process-180:
Traceback (most recent call last):
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/data1/bolt163/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/data/offline/anaconda2/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe

**Comment by pkuyym** [comment]
从log里面看不出来确切的出错位置，因为进程数比较多，queue的报错直接把真实的错误掩盖了，看起来模型已经训练了几个pass，这种随机错误最好能保留一些出错时的context

**Comment by bolt163** [comment]
说一下我跑的环境，可能跟有其他DL任务跟我抢gpu资源有关，现在出错的话解决方案是用的 init_model_path  选项把上次跑完的模型重新拉起来执行(...)

**Comment by pkuyym** [comment]
@bolt163 嗯，失败后这样resume可以的

**Comment by windowxiaoming** [comment]
EOFError可能是迭代轮换时，gpu不够导致
