### ISSUE TITLE
这是什么原因呢？

### ISSUE THREAD

**Issue by wuzong19** [PaddlePaddle/DeepSpeech#238]
-----------  Configuration Arguments -----------
augment_conf_path: conf/augmentation.config
batch_size: 16
dev_manifest: data/tiny/manifest.tiny
init_model_path: None
is_local: 1
learning_rate: 1e-05
max_duration: 27.0
mean_std_path: data/tiny/mean_std.npz
min_duration: 0.0
num_conv_layers: 2
num_iter_print: 100
num_passes: 10
num_proc_data: 1
num_rnn_layers: 3
output_model_dir: ./checkpoints/tiny
rnn_layer_size: 2048
share_rnn_weights: 0
shuffle_method: batch_shuffle_clipped
specgram_type: linear
test_off: 0
train_manifest: data/tiny/manifest.tiny
trainer_count: 2
use_gpu: 0
use_gru: 0
use_sortagrad: 1
vocab_path: data/tiny/vocab.txt
------------------------------------------------
I0527 03:22:21.053562   433 Util.cpp:166] commandline:  --use_gpu=0 --rnn_use_ba
tch=True --log_clipping=True --trainer_count=2
[INFO 2018-05-27 03:22:21,071 layers.py:2606] output for __conv_0__: c = 32, h =
 81, w = 54, size = 139968
[INFO 2018-05-27 03:22:21,074 layers.py:3133] output for __batch_norm_0__: c = 3
2, h = 81, w = 54, size = 139968
[INFO 2018-05-27 03:22:21,077 layers.py:7224] output for __scale_sub_region_0__:
 c = 32, h = 81, w = 54, size = 139968
[INFO 2018-05-27 03:22:21,079 layers.py:2606] output for __conv_1__: c = 32, h =
 41, w = 54, size = 70848
[INFO 2018-05-27 03:22:21,082 layers.py:3133] output for __batch_norm_1__: c = 3
2, h = 41, w = 54, size = 70848
[INFO 2018-05-27 03:22:21,085 layers.py:7224] output for __scale_sub_region_1__:
 c = 32, h = 41, w = 54, size = 70848
I0527 03:22:21.739264   433 GradientMachine.cpp:94] Initing parameters..
I0527 03:22:25.073403   433 GradientMachine.cpp:101] Init parameters done.
Traceback (most recent call last):
  File "train.py", line 129, in <module>
    main()
  File "train.py", line 125, in main
    train()
  File "train.py", line 116, in train
    test_off=args.test_off)
  File "/DeepSpeech/model_utils/model.py", line 155, in train
    feeding=adapted_feeding_dict)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/trainer.py", line 162,
in train
    for batch_id, data_batch in enumerate(reader()):
  File "/DeepSpeech/model_utils/model.py", line 391, in adapted_reader
    for instance in data():
  File "/DeepSpeech/data_utils/data.py", line 199, in batch_reader
    for instance in instance_reader():
  File "/DeepSpeech/data_utils/utility.py", line 178, in xreader
    manager = Manager()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 99, in Manager
    m.start()
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 524, in start
    self._process.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
Fail in training!

**Comment by jiangliuer-beep** [comment]
batch_size调小一点，文档里有写的
