### ISSUE TITLE
我训练一个汉语模型，将aishell的数据集降采样为8k的，结果不能收敛，最左还报错了。

### ISSUE THREAD

**Issue by songxia928** [PaddlePaddle/DeepSpeech#239]
...................................................................................................
Pass: 0, Batch: 100, TrainCost: 68.859889
...................................................................................................
Pass: 0, Batch: 200, TrainCost: 68.140386
...................................................................................................
Pass: 0, Batch: 300, TrainCost: 73.981499
...................................................................................................
Pass: 0, Batch: 400, TrainCost: 79.325998
...................................................................................................
Pass: 0, Batch: 500, TrainCost: 84.907326
...................................................................................................
Pass: 0, Batch: 600, TrainCost: 91.324884
...................................................................................................
Pass: 0, Batch: 700, TrainCost: 98.817860
...................................................................................................
Pass: 0, Batch: 800, TrainCost: 106.118329
...................................................................................................
Pass: 0, Batch: 900, TrainCost: 111.627918
...................................................................................................
Pass: 0, Batch: 1000, TrainCost: 85.846820
........................................................................Traceback (most recent call last):
  File "train.py", line 129, in <module>
    main()
  File "train.py", line 125, in main
    train()
  File "train.py", line 116, in train
    test_off=args.test_off)
  File "/data/chensong/code/20180522_deepspeech/DeepSpeech/model_utils/model.py", line 155, in train
    feeding=adapted_feeding_dict)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/trainer.py", line 201, in train
    gm=self.__gradient_machine__))
  File "/data/chensong/code/20180522_deepspeech/DeepSpeech/model_utils/model.py", line 140, in event_handler
    feeding=adapted_feeding_dict)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/trainer.py", line 234, in test
    evaluator=evaluator, cost=total_cost / num_samples)
ZeroDivisionError: float division by zero
Failed in training!

原始的16k的数据可以正常训练，并收敛。但降采样为8k就不行了。还有自己准备的其他8k数据也不行。
求指教！！！

**Comment by songxia928** [comment]
不好意思，是我数据问题，重新处理了一遍就好了

**Comment by liufei1656** [comment]
你的性能能够到多少？

**Comment by zongweiLi** [comment]
请问你是怎么修改的源码，我也是讲aishell 的数据集降为8k，但是在训练过程中就会报错
F0122 14:40:08.074589 142019 BlockExpandOp.cpp:73] Check failed: seqLength == outputHeight * outputWidth (43 vs. 18446744073709550799) 
*** Check failure stack trace: ***

**Comment by songxia928** [comment]
> 你的性能能够到多少？

aishell上能有9.x%

**Comment by zongweiLi** [comment]
我在训练8k的模型，也出现了不收敛的问题，请问这个问题是怎么解决的
...................................................................................................
Pass: 0, Batch: 100, TrainCost: 58.155260
...................................................................................................
Pass: 0, Batch: 200, TrainCost: 60.066805
...................................................................................................
Pass: 0, Batch: 300, TrainCost: 61.880709
...................................................................................................
Pass: 0, Batch: 400, TrainCost: 62.830801
...................................................................................................
Pass: 0, Batch: 500, TrainCost: 63.525541
...................................................................................................
