### ISSUE TITLE
error during training (tiny example)

### ISSUE THREAD

**Issue by cogmeta** [PaddlePaddle/DeepSpeech#257]
------ Time: 43 sec,  Pass: 5, ValidationCost: 253.10401535
...
------- Time: 43 sec,  Pass: 6, ValidationCost: 248.755771637
...
------- Time: 109 sec,  Pass: 7, ValidationCost: 246.753059387
...
------- Time: 108 sec,  Pass: 8, ValidationCost: 245.458805084
...
------- Time: 105 sec,  Pass: 9, ValidationCost: 242.365924835
...
------- Time: 107 sec,  Pass: 10, ValidationCost: 237.124584198
...
------- Time: 105 sec,  Pass: 11, ValidationCost: 233.543140411
.Exception in thread Thread-25:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ubuntu/DeepSpeech/data_utils/utility.py", line 153, in flush_worker
    sample = in_queue.get()
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: got end of file during message

**Comment by cogmeta** [comment]
My fault. Disk full problem...closing.
