### ISSUE TITLE
demo_client运行报错？

### ISSUE THREAD

**Issue by blood0708** [PaddlePaddle/DeepSpeech#299]
root@b766672fd554:/DeepSpeech/examples/deploy_demo# ./run_demo_client.sh 
Traceback (most recent call last):
  File "deploy/demo_client.py", line 2, in <module>
    from pynput import keyboard
  File "/usr/local/lib/python2.7/dist-packages/pynput/__init__.py", line 23, in <module>
    from . import keyboard
  File "/usr/local/lib/python2.7/dist-packages/pynput/keyboard/__init__.py", line 49, in <module>
    from ._xorg import KeyCode, Key, Controller, Listener
  File "/usr/local/lib/python2.7/dist-packages/pynput/keyboard/_xorg.py", line 39, in <module>
    from pynput._util.xorg import (
  File "/usr/local/lib/python2.7/dist-packages/pynput/_util/xorg.py", line 40, in <module>
    _check()
  File "/usr/local/lib/python2.7/dist-packages/pynput/_util/xorg.py", line 38, in _check
    display = Xlib.display.Display()
  File "/usr/local/lib/python2.7/dist-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/protocol/display.py", line 85, in __init__
    name, protocol, host, displayno, screenno = connect.get_display(display)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/support/connect.py", line 73, in get_display
    return mod.get_display(display)
  File "/usr/local/lib/python2.7/dist-packages/Xlib/support/unix_connect.py", line 61, in get_display
    raise error.DisplayNameError(display)
Xlib.error.DisplayNameError: Bad display name ""
Failed in starting demo client!

**Comment by WiliiamBryant** [comment]
你好，我也遇到了和你一样的问题，请问你最后是怎么解决的？

**Comment by blood0708** [comment]
有点记不清怎么弄的了，时间太久了

**Comment by DemoMoon** [comment]
sudo sh run_demo_client.sh 
run_demo_client.sh: line 11: 83515 Segmentation fault: 11  CUDA_VISIBLE_DEVICES=0 python3 -u deploy/demo_client.py --host_ip='xx.xx.xx.xx' --host_port=8086
Failed in starting demo client!

**Comment by DemoMoon** [comment]
Failed in starting demo client!
(venv) demodeMacBook-Pro:deploy_demo demo$ python
Python 3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyboard
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'keyboard'
>>> exit()
(venv) demodeMacBook-Pro:deploy_demo demo$ pip show keyboard
Name: keyboard
Version: 0.13.5
Summary: Hook and simulate keyboard events on Windows and Linux
Home-page: https://github.com/boppreh/keyboard
Author: BoppreH
Author-email: boppreh@gmail.com
License: MIT
Location: /Users/demo/PaddlePaddle/DeepSpeech-release-v1.8.5/tools/venv/lib/python3.7/site-packages
Requires: pyobjc
Required-by: 
(venv) demodeMacBook-Pro:deploy_demo demo$

**Comment by DemoMoon** [comment]
(venv) demodeMacBook-Pro:DeepSpeech-release-v1.8.5 demo$ CUDA_VISIBLE_DEVICES=0 python -u deploy/demo_client.py --host_ip 'xx.xx.xx.xx' --host_port 8086
Traceback (most recent call last):
  File "deploy/demo_client.py", line 2, in <module>
    import keyboard
ModuleNotFoundError: No module named 'keyboard'
(venv) demodeMacBook-Pro:DeepSpeech-release-v1.8.5 demo$ pip show keyboard
Name: keyboard
Version: 0.13.5
Summary: Hook and simulate keyboard events on Windows and Linux
Home-page: https://github.com/boppreh/keyboard
Author: BoppreH
Author-email: boppreh@gmail.com
License: MIT
Location: /Users/demo/PaddlePaddle/DeepSpeech-release-v1.8.5/tools/venv/lib/python3.7/site-packages
Requires: pyobjc
Required-by: 
(venv) demodeMacBook-Pro:DeepSpeech-release-v1.8.5 demo$

**Comment by DemoMoon** [comment]
@zh794390558 @xinghai-sun please help me ,thks
