### ISSUE TITLE
运行train.py的时候报ValueError: No such parameter错误

### ISSUE THREAD

**Issue by suntingfeng** [PaddlePaddle/DeepSpeech#368]
你好，我在进行模型训练的时候出现了以下的错误，请问这是什么原因引起的呢？该如何解决呢？谢谢！！！
-----------  Configuration Arguments -----------
augment_conf_path: conf/augmentation.configbatch_size: 256dev_manifest: ../test_manifest/manifest.dev
init_model_path: ../resource/params.tar.gz
is_local: True
learning_rate: 0.0005
max_duration: 27.0
mean_std_path: ../resource/mean_std.npz
min_duration: 0.0
num_conv_layers: 2
num_iter_print: 100
num_passes: 200
num_proc_data: 16
num_rnn_layers: 3
output_model_dir: ../output
rnn_layer_size: 2048
share_rnn_weights: True
shuffle_method: batch_shuffle_clipped
specgram_type: linear
test_off: False
train_manifest: ../test_manifest/manifest.train
trainer_count: 1
use_gpu: True
use_gru: False
use_sortagrad: True
vocab_path: ../resource/vocab.txt
------------------------------------------------
I1014 19:49:58.496965 127202 Util.cpp:166] commandline:  --use_gpu=True --rnn_use_batch=True --log_clipping=True --trainer_count=1
[INFO 2019-10-14 19:50:00,083 layers.py:2716] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2019-10-14 19:50:00,085 layers.py:3361] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2019-10-14 19:50:00,086 layers.py:7533] output for __scale_sub_region_0__: c = 32, h = 81, w = 54, size =139968
[INFO 2019-10-14 19:50:00,088 layers.py:2716] output for __conv_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2019-10-14 19:50:00,089 layers.py:3361] output for __batch_norm_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2019-10-14 19:50:00,090 layers.py:7533] output for __scale_sub_region_1__: c = 32, h = 41, w = 54, size =70848
I1014 19:50:21.294397 127202 GradientMachine.cpp:94] Initing parameters..
I1014 19:50:25.766219 127202 GradientMachine.cpp:101] Init parameters done.
/usr/lib64/python2.7/site-packages/resampy/core.py:90: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if not np.issubdtype(x.dtype, np.float):
/usr/lib64/python2.7/site-packages/resampy/core.py:90: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if not np.issubdtype(x.dtype, np.float):
/usr/lib64/python2.7/site-packages/resampy/core.py:90: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  if not np.issubdtype(x.dtype, np.float):

------- Time: 1 sec,  Pass: 0, ValidationCost: 2138.80664062
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    main()
  File "train.py", line 129, in main
    train()
  File "train.py", line 120, in train
    test_off=args.test_off)
  File "/home/rec/local_disk/template/stf/items/deepspeech2/src/model.py", line 156, in train
    feeding=adapted_feeding_dict)
  File "/usr/lib64/python2.7/site-packages/paddle/v2/trainer.py", line 214, in train
    gm=self.__gradient_machine__))
  File "/home/rec/local_disk/template/stf/items/deepspeech2/src/model.py", line 149, in event_handler
    trainer.save_parameter_to_tar(f)
  File "/usr/lib64/python2.7/site-packages/paddle/v2/trainer.py", line 134, in save_parameter_to_tar
    self.__parameters__.to_tar(f)
  File "/usr/lib64/python2.7/site-packages/paddle/v2/parameters.py", line 343, in to_tar
    self.serialize(nm, buf)
  File "/usr/lib64/python2.7/site-packages/paddle/v2/parameters.py", line 304, in serialize
    param = self.get(name)
  File "/usr/lib64/python2.7/site-packages/paddle/v2/parameters.py", line 242, in get
    return self.__getitem__(key=parameter_name)
  File "/usr/lib64/python2.7/site-packages/paddle/v2/parameters.py", line 186, in __getitem__
    return self.__getter_inner(key, api.PARAMETER_VALUE)
  File "/usr/lib64/python2.7/site-packages/paddle/v2/parameters.py", line 164, in __getter_inner
    each_gradient_machine, key)
  File "/usr/lib64/python2.7/site-packages/paddle/v2/parameters.py", line 418, in __get_parameter_in_gradient_machine__
    raise ValueError("No such parameter")
ValueError: No such parameter

**Comment by suntingfeng** [comment]
已解决
