### ISSUE TITLE
demo_server error 

### ISSUE THREAD

**Issue by cogmeta** [PaddlePaddle/DeepSpeech#40]
Exception happened during processing of request from ('10.40.0.206', 54528)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "demo_server.py", line 102, in handle
    transcript = self.server.audio_process_handler(filename)
  File "demo_server.py", line 192, in file_to_transcript
    feeding_dict=data_generator.feeding)
  File "/home/ubuntu/DeepSpeech/deploy/../model_utils/model.py", line 207, in infer_batch
    output_layer=self._log_probs, parameters=self._parameters)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/inference.py", line 50, in __init__
    val.copyFromNumpyArray(parameters.get(name).flatten())
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 242, in get
    return self.__getitem__(key=parameter_name)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 186, in __getitem__
    return self.__getter_inner(key, api.PARAMETER_VALUE)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 153, in __getter_inner
    shape = self.get_shape(key)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/parameters.py", line 200, in get_shape
    raise ValueError("No such parameter %s" % key)
ValueError: No such parameter ___recurrent_layer_0__.w0

**Comment by cogmeta** [comment]
Sorry, needed to change params to match the training ones. Closing it..

**Comment by 18811737901** [comment]
> Sorry, needed to change params to match the training ones. Closing it..

Can you tell me how to change params to match the training ones and solve this problem？Thanks.
