### ISSUE TITLE
run_train.sh出错

### ISSUE THREAD

**Issue by harold-yh** [PaddlePaddle/DeepSpeech#75]
MAC OS 10.13.2
Python版本：2.7.13
paddle版本：使用pip安装，编译安装不过。
PaddlePaddle 0.10.0, compiled with
    with_avx: ON
    with_gpu: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF
```
-----------  Configuration Arguments -----------
augment_conf_path: conf/augmentation.config
batch_size: 8
dev_manifest: data/tiny/manifest.tiny
init_model_path: None
is_local: 1
learning_rate: 1e-05
max_duration: 27.0
mean_std_path: data/tiny/mean_std.npz
min_duration: 0.0
num_conv_layers: 2
num_iter_print: 100
num_passes: 20
num_proc_data: 1
num_rnn_layers: 3
output_model_dir: ./checkpoints/tiny
rnn_layer_size: 2048
share_rnn_weights: 1
shuffle_method: batch_shuffle_clipped
specgram_type: linear
test_off: 0
train_manifest: data/tiny/manifest.tiny
trainer_count: 4
use_gpu: 0
use_gru: 0
use_sortagrad: 1
vocab_path: data/tiny/vocab.txt
------------------------------------------------
I1212 09:08:28.942749 2570847040 Util.cpp:166] commandline:  --use_gpu=0 --rnn_use_batch=True --log_clipping=True --trainer_count=4
[INFO 2017-12-12 09:08:28,953 layers.py:2479] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
Traceback (most recent call last):
  File "train.py", line 131, in <module>
    main()
  File "train.py", line 127, in main
    train()
  File "train.py", line 107, in train
    share_rnn_weights=args.share_rnn_weights)
  File "/Volumes/DATA/git/paddlepaddle/DeepSpeech/model_utils/model.py", line 46, in __init__
    rnn_layer_size, use_gru, share_rnn_weights)
  File "/Volumes/DATA/git/paddlepaddle/DeepSpeech/model_utils/model.py", line 307, in _create_network
    share_rnn_weights=share_rnn_weights)
  File "/Volumes/DATA/git/paddlepaddle/DeepSpeech/model_utils/network.py", line 263, in deep_speech_v2_network
    index_range_datas=index_range_datas)
  File "/Volumes/DATA/git/paddlepaddle/DeepSpeech/model_utils/network.py", line 165, in conv_group
    index_range_data=index_range_datas[0])
  File "/Volumes/DATA/git/paddlepaddle/DeepSpeech/model_utils/network.py", line 43, in conv_bn_layer
    scale_sub_region = paddle.layer.scale_sub_region(
AttributeError: 'module' object has no attribute 'scale_sub_region'
Fail in training!
```

**Comment by harold-yh** [comment]
编译安装的最新版本也是0.10.0，运行sh setup.sh报错

**Comment by kuke** [comment]
你从源码编译paddle的0.10.0版还是会遇到一样的问题，一定要编译```develop```分支。运行setup.sh的报错可以通过注释掉[报错行](https://github.com/PaddlePaddle/DeepSpeech/blob/develop/decoders/swig/setup.py#L65)来解决。

**Comment by harold-yh** [comment]
目前paddlepaddle的master分支没有代码，所以我编译的也只能是develop分支
