### ISSUE TITLE
 IOError: got end of file during message when  training with CPU

### ISSUE THREAD

**Issue by witkeyshare** [PaddlePaddle/DeepSpeech#96]
root@537527a1fed8:/DeepSpeech/examples/tiny# sh run_train.sh
-----------  Configuration Arguments -----------
augment_conf_path: conf/augmentation.config
batch_size: 2
dev_manifest: data/tiny/manifest.tiny
init_model_path: None
is_local: 1
learning_rate: 1e-05
max_duration: 27.0
mean_std_path: data/tiny/mean_std.npz
min_duration: 0.0
num_conv_layers: 2
num_iter_print: 100
num_passes: 10
num_proc_data: 1
num_rnn_layers: 3
output_model_dir: ./checkpoints/tiny
rnn_layer_size: 2048
share_rnn_weights: 1
shuffle_method: batch_shuffle_clipped
specgram_type: linear
test_off: 0
train_manifest: data/tiny/manifest.tiny
trainer_count: 4
use_gpu: 0
use_gru: 0
use_sortagrad: 1
vocab_path: data/tiny/vocab.txt
------------------------------------------------
I1222 08:04:21.331934 17693 Util.cpp:166] commandline:  --use_gpu=0 --rnn_use_batch=True --log_clipping=True --trainer_count=4
[INFO 2017-12-22 08:04:21,345 layers.py:2696] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2017-12-22 08:04:21,347 layers.py:3264] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2017-12-22 08:04:21,347 layers.py:7436] output for __scale_sub_region_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2017-12-22 08:04:21,348 layers.py:2696] output for __conv_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2017-12-22 08:04:21,348 layers.py:3264] output for __batch_norm_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2017-12-22 08:04:21,349 layers.py:7436] output for __scale_sub_region_1__: c = 32, h = 41, w = 54, size = 70848
I1222 08:04:21.697677 17693 GradientMachine.cpp:94] Initing parameters..
I1222 08:04:23.947732 17693 GradientMachine.cpp:101] Init parameters done.

.Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 153, in flush_worker
    sample = in_queue.get()
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: got end of file during message

need to set something ?

**Comment by kuke** [comment]
Could you please train the model on another platform with NV's GPU? Something weird may happen when running the Docker image with nvidia-docker.

**Comment by witkeyshare** [comment]
i justin use paddlepaddle/paddle docker images and install essential libraries and run tiny train command.

this program can't run in cpu mode?

**Comment by kuke** [comment]
Which Docker image do you use, is it ```paddlepaddle/paddle:latest```. This program definitely can run in CPU mode, but I am not sure there is no problem with your installation.

**Comment by fantasyoooo** [comment]
求助求助..
在单个NV M40 GPU训练下也出现了类似的问题..
已经到了第15个epoch了,突然就中断了..
问题反复提醒了几次..

Pass: 15, Batch: 4900, TrainCost: 0.721754
...................................................................................................
Pass: 15, Batch: 5000, TrainCost: 0.887054
...Exception in thread Thread-32:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 153, in flush_worker
    sample = in_queue.get()
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: got end of file during message

Process Process-565:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-562:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process Process-569:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-560:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 121, in order_read_worker
    in_queue.put((order_id, sample))
  File "<string>", line 2, in put
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
Process Process-574:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
Process Process-571:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-566:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-568:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-576:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
.
.
.

**Comment by fantasyoooo** [comment]
batch_size已经从64改成了24..

**Comment by wuqi2547997322** [comment]
我用nvidia-docker（sudo nvidia-docker run -it -v $(pwd)/DeepSpeech:/DeepSpeech paddlepaddle/deep_speech:latest-gpu /bin/bash）在8块显卡上跑训练程序DeepSpeech/aishell/run_train.sh，出错了，请问这是怎么回事？

Pass: 9, Batch: 1500, TrainCost: 1.245488
...................................................................................................
Pass: 9, Batch: 1600, TrainCost: 1.278968
...................................................................................................
Pass: 9, Batch: 1700, TrainCost: 1.278138
...................................................................................................
Pass: 9, Batch: 1800, TrainCost: 1.370887
...........................................................................
------- Time: 2829 sec,  Pass: 9, ValidationCost: 1.88582897921
...................................................................................................Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 153, in flush_worker
    sample = in_queue.get()
  File "<string>", line 2, in get
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer


Pass: 10, Batch: 100, TrainCost: 0.892535
.....................................Process Process-376:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-373:
Process Process-372:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
    self.run()
IOError: [Errno 104] Connection reset by peer
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
Process Process-367:
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
Process Process-371:
Traceback (most recent call last):
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    kind, result = conn.recv()
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
EOFError
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
Process Process-374:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
Process Process-368:
Traceback (most recent call last):
    while order_id != out_order[0]:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 138, in order_handle_worker
    kind, result = conn.recv()
    out_order[0] += 1
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
Process Process-365:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    kind, result = conn.recv()
EOFError
Process Process-375:
IOError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-364:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-369:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-370:
Process Process-377:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-362:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 121, in order_read_worker
    in_queue.put((order_id, sample))
  File "<string>", line 2, in put
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
Process Process-363:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-366:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
Process Process-378:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
    self._target(*self._args, **self._kwargs)
  File "/DeepSpeech/data_utils/utility.py", line 135, in order_handle_worker
    while order_id != out_order[0]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
