### ISSUE TITLE
demo_client.py IOError: [Errno -9996] Invalid input device (no default output device)

### ISSUE THREAD

**Issue by witkeyshare** [PaddlePaddle/DeepSpeech#98]
/usr/bin/python2.7 /media/justin/新加卷1/deepspeech/DeepSpeech/deploy/demo_client.py
Traceback (most recent call last):
  File "/media/justin/新加卷1/deepspeech/DeepSpeech/deploy/demo_client.py", line 94, in <module>
    main()
  File "/media/justin/新加卷1/deepspeech/DeepSpeech/deploy/demo_client.py", line 79, in main
    stream_callback=callback)
  File "build/bdist.linux-x86_64/egg/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno -9996] Invalid input device (no default output device)

Process finished with exit code 1

import _portaudio as pa
pa.get_version()
1246720L
pa.get_version_text()
u'PortAudio V19.6.0-devel, revision 396fe4b6699ae929d3a685b3ef8a7e97396139a4'
pa.get_device_count()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
IOError: [Errno -10000] PortAudio not initialized
pa.initialize()
pa.get_device_count()
0L

PyAudio  _version__ = "0.2.11"

anyone tell me why?

**Comment by kuke** [comment]
Seems that you don't have a valid audio input device. To run the demo client, you need to check that first.

**Comment by Arch-gx** [comment]
Hello, has the problem been solved? I met the same problem on Ubuntu.
